# Generated by Django 5.2 on 2025-05-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='unique_id',
        ),
    ]
