# Generated by Django 5.2 on 2025-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per person', max_digits=10)),
                ('image', models.ImageField(upload_to='services/catering/')),
                ('cuisine_type', models.CharField(max_length=100)),
                ('min_order_quantity', models.IntegerField(help_text='Minimum number of persons')),
                ('includes_serving_staff', models.BooleanField(default=False)),
                ('includes_setup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='services/events/')),
                ('event_type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(help_text='Maximum number of guests')),
                ('duration', models.IntegerField(help_text='Duration in hours')),
                ('includes_decoration', models.BooleanField(default=False)),
                ('includes_catering', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='services/photography/')),
                ('shoot_type', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in hours')),
                ('includes_editing', models.BooleanField(default=True)),
                ('number_of_photos', models.IntegerField(help_text='Minimum number of delivered photos')),
                ('includes_prints', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per piece', max_digits=10)),
                ('image', models.ImageField(upload_to='services/printing/')),
                ('print_type', models.CharField(max_length=100)),
                ('paper_type', models.CharField(max_length=100)),
                ('min_order_quantity', models.IntegerField()),
                ('includes_design', models.BooleanField(default=False)),
                ('delivery_time', models.IntegerField(help_text='Delivery time in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
