# Generated by Django 5.2rc1 on 2025-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cart_cartitem_order_orderitem_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['title'], name='core_servic_title_06a5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='core_servic_price_72c8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['name'], name='core_servic_name_49460b_idx'),
        ),
        migrations.AddIndex(
            model_name='storecategory',
            index=models.Index(fields=['name'], name='core_storec_name_7ba441_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['name'], name='core_storei_name_0c8d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['price'], name='core_storei_price_1799a9_idx'),
        ),
    ]
