# Generated by Django 5.2rc1 on 2025-05-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='core_bookin_service_c5dd06_idx',
            old_name='core_bookin_service_5c7d5a_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='core_bookin_user_id_aa888a_idx',
            old_name='core_bookin_user_id_dd1660_idx',
        ),
    ]
