# Generated by Django 5.2rc1 on 2025-12-08 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_core_bookin_service_5c7d5a_idx_core_bookin_service_c5dd06_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin assigned to this chat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='subject',
            field=models.CharField(blank=True, default='Support Chat', max_length=200),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['admin', '-last_message_at'], name='core_chat_admin_i_65f531_idx'),
        ),
    ]
