# Generated by Django 5.2rc1 on 2025-12-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_conversation_conversationmessage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
