# Generated by Django 5.2rc1 on 2025-12-09 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_chat_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='email', max_length=20)),
                ('service_type', models.CharField(choices=[('event', 'Event Management'), ('photo', 'Photography'), ('catering', 'Catering'), ('printing', 'Printing Service'), ('store', 'Store Item'), ('general', 'General Inquiry')], default='general', max_length=20)),
                ('service_id', models.PositiveIntegerField(blank=True, help_text='ID of the related service/item if applicable', null=True)),
                ('service_name', models.CharField(blank=True, help_text='Name of the service/item being inquired about', max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='core_contac_email_800caf_idx'), models.Index(fields=['-created_at'], name='core_contac_created_5d3c34_idx'), models.Index(fields=['service_type', 'service_id'], name='core_contac_service_c59267_idx')],
            },
        ),
    ]
