"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.

Environment strategy:
- Local dev: Uses SQLite (db.sqlite3), DEBUG=True by default
- Production (Vercel): Uses Aiven MySQL via DATABASE_URL, PyMySQL driver, DEBUG=False
"""

from pathlib import Path
import os
import dj_database_url

# Load environment variables from .env files
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# CORE SETTINGS
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-change-this-in-production-use-env-var'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False in production, True in local development
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# Determine if we're running in production (on Vercel or with DATABASE_URL)
IS_PRODUCTION = not DEBUG or bool(os.getenv('DATABASE_URL'))

# Configure ALLOWED_HOSTS for local and production
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.vercel.app',
]

# Add Vercel deployment URL if set
vercel_url = os.getenv('VERCEL_URL')
if vercel_url and vercel_url not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(vercel_url)

# Add custom domain if set
custom_domain = os.getenv('CUSTOM_DOMAIN')
if custom_domain and custom_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(custom_domain)


# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'crispy_forms',
    'crispy_bootstrap5',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise for static files (important for Vercel)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.views.service_categories_processor',
                'core.views.store_categories_processor',
                'core.views.cart_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'

# Crispy forms bootstrap version
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Production: Use Aiven MySQL with PyMySQL driver
    db_config = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    
    # Force MySQL backend with PyMySQL driver
    db_config['ENGINE'] = 'django.db.backends.mysql'
    
    # Handle SSL for Aiven MySQL
    # Aiven requires SSL. If DATABASE_URL contains ssl-mode=REQUIRED,
    # we need to remove it because PyMySQL doesn't accept that parameter.
    # Instead, we configure SSL via OPTIONS.
    options = db_config.get('OPTIONS', {})
    options.pop('ssl-mode', None)  # Remove Aiven's ssl-mode parameter
    
    # Configure PyMySQL SSL settings for Aiven
    # PyMySQL expects ssl as a dict with ca, cert, key, etc.
    # For Aiven, we typically just need to enable SSL.
    if 'ssl' not in options:
        options['ssl'] = {'ca': None}  # Let system use default CA bundle
    
    db_config['OPTIONS'] = options
    # Add connection pooling settings
    db_config['CONN_MAX_AGE'] = 600
    db_config['ATOMIC_REQUESTS'] = False
    db_config['AUTOCOMMIT'] = True
    DATABASES = {'default': db_config}
else:
    # Local development: Use SQLite (no internet/Aiven required)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'ATOMIC_REQUESTS': False,
            'AUTOCOMMIT': True,
        }
    }


# ==============================================================================
# CHANNELS CONFIGURATION
# ==============================================================================

# Use in-memory channel layer (sufficient for Vercel without Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# WebSocket configuration
WEBSOCKET_ACCEPT_TIME = 20
WEBSOCKET_TIMEOUT = 3600


# ==============================================================================
# SESSIONS AND SECURITY
# ==============================================================================

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400 * 7  # 7 days
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Default: insecure for local development
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False

# Production security settings (applied when DEBUG=False)
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Prevent content sniffing
    SECURE_CONTENT_SECURITY_POLICY = {
        'default-src': ("'self'",),
    }


# ==============================================================================
# PASSWORD VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# STATIC FILES
# ==============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise storage for efficient static file serving on Vercel
if IS_PRODUCTION:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'


# ==============================================================================
# MEDIA FILES
# ==============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# MESSAGE TAGS FOR BOOTSTRAP
# ==============================================================================

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


# ==============================================================================
# AUTHENTICATION AND REDIRECTS
# ==============================================================================

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'


# ==============================================================================
# CACHING
# ==============================================================================

# Use local memory cache for development, database cache for production
if IS_PRODUCTION:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache_table',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
